name: Deploy to Production

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          ssh -p 4545 $SERVER_USER@$SERVER_IP "
            cd /home/new10s/newTens2.0 &&
            git pull origin production &&
            cd ./client
            npm install &&
            npm run build &&
            cd ../server &&
            npm install &&
            pm2 restart all &&
            sudo systemctl reload nginx
          "
