name: Build and Deploy to Production

on:
  push:
    branches:
      - production  # Trigger deployment on changes to the production branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files in the directory
        run: ls -R /home/runner/work/newTens2.0/newTens2.0  # List all files in the project directory

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Match this to your server's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Vite build command

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          eval "$(ssh-agent -s)"
          echo "$SSH_PRIVATE_KEY" | ssh-add -
          rsync -avz --delete ./dist/ $SERVER_USER@$SERVER_IP:/home/new10s/newTens2.0/client/dist
          ssh $SERVER_USER@$SERVER_IP "pm2 restart all"  # Restart PM2 processes
          ssh $SERVER_USER@$SERVER_IP "sudo systemctl reload nginx"  # Reload Nginx if needed
